### ISSUE TITLE
The ADOHTTPClient class should support URL overrides

### ISSUE THREAD

**Issue by natemcfeters** [microsoft/simple_ado#12]
While the class is helpful for the default collections case / visualstudio, I've found that it has a number of issues with URLs like dev.azure.com, when interacting with those sites via the api_endpoint method. In these cases, I think that if you allow a URL that's the full /_git/{project_name} override to be passed in, you could simply replace _git with _apis and achieve the necessary result.

Open to alternative ideas?

**Comment by dalemyers** [comment]
Sorry I'm not quite following what you are suggesting here?

For some background: Yeah, I think this is still using the old format URL generally and expects it to only be the default collection. I'm not sure how many out there actually use multiple collections. If I recall correctly, they can only be created on TFS? I think this should focus just on ADO and not any legacy tooling.

**Comment by natemcfeters** [comment]
Well, I'm a Microsoft employee, we've got multiple ADO apps with some varying paths and challenges. I'm not sure what I can share in comments here on that, but suffice it to say there's a minimum of 3 different types of processing that I'm aware of. 

I'm not sure how necessary this would be to most people's use case... I would assume most people simply need it to work for their one ADO solution. 

For me, I was seeking to leverage simple_ado to build a quick python script that can take a massive list of repos, from varied servers, and grab all of the source code down to local.

**Comment by dalemyers** [comment]
It's definitely doable without breaking the API. Instead of `is_default_collection` in `api_endpoint()` on HTTPClient, you can just have `collection="DefaultCollection"` as the default and then have the various callers adjust to set the collection instead.

**Comment by natemcfeters** [comment]
I managed to solve this for my case without making any changes, was just slightly different on how to call it than what I was originally expecting, so I think this one is on me, and will close it.
