### ISSUE TITLE
Unsure of how to use the project to complete an API request

### ISSUE THREAD

**Issue by lochlannyeal** [microsoft/simple_ado#4]
I am unsure of how to create a new work item using this. I can create a very simple create request using the 'requests' module to complete this however on doing so I am unaware of how to set the WorkItemType etc. Looking into simple_ado there seems to be a lot of functionality but I am just unsure of how to utilize this. I have my PAT and URL as well as what fields I'd like to populate when creating a new WorkItem but am just unaware of how to do so. In a very sad pseudocode effort this is the kind of thing I am trying to acheive:

```
Import simple_ado

pat = '***************'
url = 'https://dev.azure.com/lochlannyeal/lochlannyeal'

fields = ["title","status","WorkItemType"]
input = ["Hello","In Progress","Issue"]

simple_ado.createWorkItem(fields, input)
    
```

**Comment by dalemyers** [comment]
Sorry for the delay in responding here. 

So, to create a work item, you are going to create your client as normal first:

```python
import simple_ado

client = simple_ado.ADOClient(tenant="whatever", credentials=("username", "pat")
```

Then you are going to use the `workitems` property on the client. and call create. 

```python
client.workitems.create(
    item_type="Bug", # This will depend on your own project
    operations=list_of_operations,
    project_id="id of your project",
)```

The unusual part here is the `list_of_operations`. This is basically how you tell ADO which properties on the ticket to set. The type of that variable is `List[AddOperation]`. So you might have something like:

```python
list_of_operations = [
    simple_ado.AddOperation("/fields/System.Title", "My new ticket"),
    simple_ado.AddOperation("/fields/System.Description", "This is an example new ticket"),
]
```

The fields depend on how your tickets are configured. You'll have a few standard ones like title and description, but your own will be different. How do you get those in the first place? Well, there's a call for that too:

```python
response = client.workitems.get_work_item_types("project_id")
```

This will give you all the work item types and there's a property called "fields" which lists all the fields on that ticket type.

Hope this helps!

**Comment by lochlannyeal** [comment]
Ah this is brilliant! This clears everything up! It's much cleaner than using the API, thank you for this, this project has a low of power for people who use DevOps and want to integrate with other systems or external data!
